spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  velocity:
    cache: false

server:
  port: 8080

management:
  port: 8081

endpoints:
  shutdown:
    enabled: true